# KAS keypairs for OpenTDF platform
# Generated by Terraform so the public keys are available for
# both the platform config and the KAS registry provisioning.

resource "tls_private_key" "kas_rsa" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "kas_rsa" {
  private_key_pem = tls_private_key.kas_rsa.private_key_pem
  subject {
    common_name = "kas-rsa"
  }
  validity_period_hours = 8760 # 1 year
  allowed_uses          = ["digital_signature", "key_encipherment"]
}

resource "tls_private_key" "kas_ec" {
  algorithm   = "ECDSA"
  ecdsa_curve = "P256"
}

resource "tls_self_signed_cert" "kas_ec" {
  private_key_pem = tls_private_key.kas_ec.private_key_pem
  subject {
    common_name = "kas-ec"
  }
  validity_period_hours = 8760
  allowed_uses          = ["digital_signature"]
}
